### ISSUE TITLE
Where is ipad, iphone etc?

### ISSUE THREAD

**Issue by sapzxc** [zsxsoft/php-useragent#11]
http://project.zsxsoft.com/useragent.js/supported.html
Why there does not listed any apple devices and platforms? I found only "safari mobile" and thats all.

**Comment by sapzxc** [comment]
But actually tested on iphone, it say "Iphone iOS 9.3.1"

**Comment by zsxsoft** [comment]
I improved iOS detection in the latest release of PHP version, but I didn't do the same thing in JS version.

**Comment by zsxsoft** [comment]
Updated
