### ISSUE TITLE
win7的图标是XP的图标，请更新

### ISSUE THREAD

**Issue by hulang** [zsxsoft/php-useragent#13]
win7 16x16 win-4.png
win7 24x24 win-4.png

**Comment by zsxsoft** [comment]
XP的图标是win-2.png，你对比一下就能发现有不同的。http://project.zsxsoft.com/useragent.js/supported.html

Date: Tue, 3 May 2016 22:48:33 -0700

**Comment by hulang** [comment]
我说的想明显的问题。。win7的图标应该和Vista差不多。圆形的

难道你的点win7系统左下角的开始菜单是和你说的类似XP的图标？

我也是醉了

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/15071174/2d6edb4e-13bc-11e6-955c-1915ae855eaa.png)
https://blogs.windows.com/windowsexperience/2012/02/17/redesigning-the-windows-logo/

微软官方的《Redesigning the Windows Logo》用的就是这个。
