### ISSUE TITLE
这些OS版本显示不出来

### ISSUE THREAD

**Issue by hulang** [zsxsoft/php-useragent#16]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by zsxsoft** [comment]
居然还有人关注这个库诶，我回头去修一下

**Comment by hulang** [comment]
@zsxsoft 回复的真快啊。
OS: Mac OS X 10.7.5 (Name = Mac OS X 10.7.5, Version = )
都显示到：name里面去了。我一直关注的啊，好多项目必用老大你出品的。。

**Comment by zsxsoft** [comment]
正好看到而已……
