### ISSUE TITLE
华为荣耀6 (H60-L11)识别为Android

### ISSUE THREAD

**Issue by elrichuang** [zsxsoft/php-useragent#2]
UserAgent: Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; H60-L11 Build/HDH60-L11) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025410 Mobile Safari/533.1 MicroMessenger/6.1.0.66_r1062275.542 NetType/WIFI

其中HDH60-L11代表华为荣耀6。

你的这个库做得很棒，请问如果我想补充规则或者扩展应该怎样做好呢？

**Comment by zsxsoft** [comment]
华为（和相当一部分厂商）的话主要的麻烦在于部分机型的UserAgent没有明显的huawei标识，贸然用通用规则识别的话误判可能性比较大。所以我一直没加。。

加规则的话，可见我的Commit Log。基本上一条Log只有一条规则加减。不过代码挺糟的样子。加完后记得跑phpunit测下。

发自我的 Windows Phone
