### ISSUE TITLE
是否考虑使用图标字体而非图片？

### ISSUE THREAD

**Issue by kuoruan** [zsxsoft/php-useragent#4]
你好，我关注这个项目有一段时间了，我一直有个想法，希望能使用图标字体而非图片来显示UA，但是一直没能找到比较全的字库。希望作者能考虑一下我的想法，感谢！
http://vorillaz.github.io/devicons/#/dafont
http://www.iconfont.cn/

**Comment by zsxsoft** [comment]
可以考虑啊，只是没时间……

**Comment by zsxsoft** [comment]
刚才没反应过来，现在想想不太行。
我这里的图标全部都是PNG，要转WebFont的话得让它们变成SVG才行，这个坑爹啊。

**Comment by kuoruan** [comment]
主要是在我看来，没必要所有的客户端都显示具体的图片，如果内核是一类的话，就显示相同的图片或者图标就行了。

**Comment by zsxsoft** [comment]
这样的话，我觉得你没有用这个库的必要。分别进行以下判断即可（按优先级）：
Trident: MSIE
EdgeHTML: Edge
Blink: Chrome
Webkit: AppleWebkit
Gecko: Gecko
