### ISSUE TITLE
Undefined offset: 1, on zsxsoft/php-useragent/lib/useragent_detect_os.php:274

### ISSUE THREAD

**Issue by sapzxc** [zsxsoft/php-useragent#5]
UserAgent: Mozilla/5.0 (X11; Linux i686; Lubuntu*Pack 14.04.2 UALinux) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.0 Maxthon/1.0.5.3 Safari/537.36

Notice: Undefined offset: 1, on zsxsoft/php-useragent/lib/useragent_detect_os.php:274

I have errors related to this user agent. Could you see, please?

**Comment by zsxsoft** [comment]
I know how to fix it, but I'm afraid that I have no time to update it now.. You can fix it yourself and create a pull request to me, I will merge it ASAP.

All you need to do is, move line 274-278 before line 272. I will do code pretty, complete unit test and fix other similar bugs in Saturday evening(GMT +8).

Sent from Outlook Mobile

On Sun, Jan 17, 2016 at 3:35 AM -0800, "Sap" notifications@github.com wrote:

UserAgent: Mozilla/5.0 (X11; Linux i686; Lubuntu*Pack 14.04.2 UALinux) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.0 Maxthon/1.0.5.3 Safari/537.36

Notice: Undefined offset: 1, on zsxsoft/php-useragent/lib/useragent_detect_os.php:274

I have errors related to this user agent. Could you see, please?

---

Reply to this email directly or view it on GitHub:
https://github.com/zsxsoft/php-useragent/issues/5
