### ISSUE TITLE
Move the test data to a seperate file (or at least method)

### ISSUE THREAD

**Issue by ThaDafinser** [zsxsoft/php-useragent#9]
I would like to use the user agent lists, to be added to the user agent comparison
But therefor the data need to be seperate
https://github.com/zsxsoft/php-useragent/blob/master/tests/TestUserAgent.php#L27-L31

**Comment by zsxsoft** [comment]
The first version of this test was built by another script, and it is such a hard work to separate them now. I will do it if I have nothing else can I do.

**Comment by zsxsoft** [comment]
I'm sorry that I didn't get you just now. This Saturday...
